election/urls.py
from django.urls import path

from .views import *

app_name="election"

urlpatterns = [
    path(r"", liste_candidats, name="liste_candidats"),
    path("candidat/liste", liste_candidats, name="liste_candidats"),
    path("candidat/detail/<int:id_candidat>", detail_candidat, name="detail_candidat"),
    path("candidat/ajout", ajout_candidat, name="ajout_candidat"),
    path("bureau/liste", liste_bureaux, name="liste_bureaux"),
    path("bureau/ajout", ajout_bureau, name="ajout_bureau"),
    path("electeur/ajout", ajout_electeur, name="ajout_electeur"),
    path("electeur/liste", liste_electeurs, name="liste_electeurs"),
    path("conseil/liste", ConseilList.as_view(), name="liste_conseils"),
    path("conseil/ajout", ConseilCreate.as_view(), name="ajout_conseil"),
    path("vote/", VoteView.as_view(), name="vote"),
    path("resultats/", ResultatsView.as_view(), name="resultats"),
]

vote_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('election.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

election/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Conseil(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Electeur(models.Model):
    date_naissance = models.DateField()
    lieu_naissance = models.CharField(max_length=50)
    numero_cni = models.CharField(max_length=15)
    a_vote = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bureau = models.ForeignKey("Bureau", on_delete=models.CASCADE)
    candidat = models.ForeignKey("Candidat", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.numero_cni

    def vote(self, candidat):
        self.candidat = candidat
        self.a_vote = True
        self.save()


class Candidat(models.Model):
    parti = models.CharField(max_length=100)
    date_naissance = models.DateField()
    slogan = models.CharField(max_length=100)
    programme = models.TextField()
    nb_voix = models.IntegerField(default=0)

    def __str__(self):
        return self.parti

    def ajout_vote(self):
        self.nb_voix += 1
        self.save()


class Bureau(models.Model):
    nom = models.CharField(max_length=255)
    lieu = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom

election/forms.py
from django import forms

from .models import *

from django.utils import timezone


class CandidatForm(forms.ModelForm):
    class Meta:
        model = Candidat
        exclude = ['nb_voix']


class BureauForm(forms.ModelForm):
    class Meta:
        model = Bureau
        fields = ('nom', 'lieu')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password')


class ElecteurForm(forms.ModelForm):
    class Meta:
        model = Electeur
        fields = ('date_naissance', 'lieu_naissance', 'numero_cni', 'bureau', 'user')

    def get_age(self, born):
        date_jour = timezone.now()
        return date_jour.year - born.year - ((date_jour.month, date_jour.day) < (born.month, born.day))

    def clean_date_naissance(self):
        date_naissance = self.cleaned_data['date_naissance']
        if self.get_age(date_naissance) < 18:
            raise forms.ValidationError('Désolé mais vous n\'êtes pas encore majeur!')
        return date_naissance


ElecteurFormSet = forms.inlineformset_factory(User, Electeur, form=ElecteurForm, can_delete=False, extra=1)


class VoteForm(forms.Form):
    candidats = forms.ModelChoiceField(queryset=Candidat.objects.all())

election/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from .models import *
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import *

# Create your views here.
def liste_candidats(request):
    #Vue renvoyant à l'utilisateur la liste des candidats de l'élection
    candidats = Candidat.objects.all()
    contexte = {
        'liste' : candidats
    }
    return render(request, 'election/candidats.html', contexte)


def detail_candidat(request, id_candidat):
    #Vue renvoyant le détail d'un candidat
    candidat = get_object_or_404(Candidat, pk=id_candidat)
    return render(request, 'election/candidat.html', {'candidat' : candidat})


def ajout_candidat(request):
    #Vue permettant l'ajout d'un nouveau candidat
    if request.method == 'POST':
        form = CandidatForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/candidat/liste')
    else:
        form = CandidatForm()
        return render(request, 'election/ajout_candidat.html', {'form' : form})


def ajout_bureau(request):
    # Vue permettant l'ajout d'un nouveau bureau de vote
    if request.method=="POST":
        form = BureauForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('election:liste_bureaux')
    form = BureauForm()
    return render(request, 'election/ajout_bureau.html', {'form' : form})

def liste_bureaux(request):
    #Liste des bureaux
    bureaux = Bureau.objects.all()
    return render(request, 'election/bureaux.html', {'bureaux' : bureaux})


def ajout_electeur(request):
    #Vue pour ajouter un nouvel électeur
    if request.method=="POST":
        form = UserForm(request.POST)
        formset = ElecteurFormSet(request.POST)
        if form.is_valid() and formset.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            formset.instance = user
            if formset.is_valid():
                formset.save()
                return redirect('election:liste_electeurs')
        else:
            return render(request, 'election/ajout_electeur.html', {'form' : form, 'formset' : formset})
    form = UserForm()
    formset = ElecteurFormSet()
    contexte = {
        'form' : form,
        'formset' : formset
    }
    return render(request, 'election/ajout_electeur.html', contexte)


@login_required
def liste_electeurs(request):
    # Liste des électeurs
    electeurs = Electeur.objects.all()
    return render(request, 'election/electeurs.html', {'electeurs' : electeurs})


class ConseilCreate(CreateView):
    model = User
    fields = ['first_name', 'last_name', 'username', 'password']
    template_name = 'election/ajout_conseil.html'
    success_url = reverse_lazy('election:liste_conseils')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.set_password(form.cleaned_data['password'])
        self.object.save()
        Conseil.objects.create(user=self.object)
        return redirect(self.success_url)



class ConseilList(ListView):
    model = Conseil
    template_name = 'election/conseils.html'


class VoteView(LoginRequiredMixin, View):
    """
    View permettant à un utilisateur d'effectuer un vote
    """
    login_url = '/accounts/login/'

    def get(self, request, *args, **kwargs):
        user = request.user
        if user.electeur_set.first().a_vote:
            return redirect('election:resultats')
        form = VoteForm()
        return render(request, 'election/vote.html', {'form' : form})

    def post(self, request, *args, **kwargs):
        form = VoteForm(request.POST)
        if form.is_valid():
            candidat = form.cleaned_data['candidats']
            user = request.user
            electeur = user.electeur_set.first()
            electeur.vote(candidat)
            candidat.ajout_vote() #On incrémente le nb_voix
            return redirect('election:resultats')


class ResultatsView(ListView):
    model = Candidat
    template_name = 'election/resultats.html'

election/templates/election/ajout_bureau.html
<h2>Ajouter un bureau</h2>

<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Valider">
</form>

election/templates/election/ajout_candidat.html
<h2>Formulaire d'ajout de candidat</h2>

<form action="#" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Validez">
</form>

election/templates/election/ajout_conseil.html
{% extends 'election/base.html' %}

{% block content %}
<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Valider">
</form>
{% endblock %}

election/templates/election/ajout_electeur.html
<h2>Ajouter un nouvel électeur</h2>

<form action="#" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ formset.as_p }}
    <input type="submit" value="Valider">
</form>

election/templates/election/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <title>Vote app</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Vote 2022</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'election:liste_candidats' %}">Accueil <span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'election:liste_electeurs' %}">Electeurs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'election:liste_conseils' %}">Membres du conseil constitutionnel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'election:liste_bureaux' %}">Bureaux</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'election:vote' %}">Je vote!</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'election:resultats' %}">Resultats provisoires</a>
            </li>
        </ul>
    </div>
</nav>


{% block content %}

{% endblock %}


<!-- Footer -->
<footer class="page-footer font-small blue pt-4">


    <!-- Copyright -->. 
    <!-- Copyright -->

</footer>
<!-- Footer -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

election/templates/election/bureaux.html
{% extends 'election/base.html' %}

{% block content %}
<h2>Liste des bureaux de vote</h2>

<table>
    <tr>
        <th>Identifiant</th>
        <th>Nom du bureau</th>
        <th>Lieu</th>
    </tr>
    {% for bureau in bureaux %}
    <tr>
        <td>{{ bureau.pk }}</td>
        <td>{{ bureau.nom }}</td>
        <td>{{ bureau.lieu }}</td>
    </tr>
    {% endfor %}
</table>

<div>
    <a href="{% url 'election:ajout_bureau' %}">Ajouter un nouveau bureau</a>
</div>
{% endblock %}

election/templates/election/candidat.html
<h3>Détail du candidat : {{ candidat.parti }}</h3>

<table>
    <thead>
        <th>Parti</th>
        <th>Date de naissance</th>
        <th>Slogan</th>
        <th>Programme</th>
        <th>Nombre de voix obtenues</th>
    </thead>
    <tbody>
        <tr>
            <td>{{ candidat.parti }}</td>
            <td>{{ candidat.date_naissance|date:"d-m-Y" }}</td>
            <td>{{ candidat.slogan }}</td>
            <td>{{ candidat.programme }}</td>
            <td>{{ candidat.nb_voix }}</td>
        </tr>
    </tbody>
</table>

election/templates/election/candidats.html
{% extends 'election/base.html' %}

{% block content %}
<h2>Liste des candidats</h2>

<table>
    <thead>
        <th>Identifiant</th>
        <th>Parti</th>
        <th>Slogan</th>
        <th>Nombre de voix</th>
        <th>Actions</th>
    </thead>
    <tbody>
        {% for candidat in liste %}
            <tr>
                <td>{{ candidat.pk }}</td>
                <td>{{ candidat.parti }}</td>
                <td>{{ candidat.slogan }}</td>
                <td>{{ candidat.nb_voix }}</td>
                <td><a href="{% url 'election:detail_candidat' candidat.pk %}">Voir détails</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div>
    <a href="{% url 'election:ajout_candidat' %}">Ajouter un candidat</a>
</div>


{% endblock %}

election/templates/election/conseils.html
{% extends 'election/base.html' %}

{% block content %}
    <ul>
        {% for conseil in object_list %}
            <li>{{ conseil.user.get_full_name }}</li>
        {% empty %}
            <p>Il n'y a pas encore de membre du conseil!</p>
        {% endfor %}
    </ul>

    <div>
        <a href="{% url 'election:ajout_conseil' %}">Ajouter un membre</a>
    </div>

{% endblock %}

election/templates/election/electeurs.html
{% extends 'election/base.html' %}

{% block content %}
<h2>Liste des électeurs</h2>

<table>
    <tr>
        <th>Nom complet</th>
        <th>Numéro CNI</th>
        <th>Date de naissance</th>
        <th>Lieu de naissance</th>
        <th>A voté</th>
        <th>Bureau de vote</th>
    </tr>
    {% for electeur in electeurs %}
    <tr>
        <td>{{ electeur.user.get_full_name }}</td>
        <td>{{ electeur.numero_cni }}</td>
        <td>{{ electeur.date_naissance|date:"d-m-Y" }}</td>
        <td>{{ electeur.lieu_naissance }}</td>
        <td>{{ electeur.a_vote|yesno:"Oui,Non,Peut-être" }}</td>
        <td>{{ electeur.bureau.nom }}</td>
    </tr>
    {% endfor %}
</table>

<div>
    <a href="{% url 'election:ajout_electeur' %}">Ajouter un électeur</a>
</div>

{% endblock %}

election/templates/election/resultats.html
{% extends 'election/base.html' %}

{% block content %}
    <table>
        <tr>
            <th>Parti du Candidat</th>
            <th>Nombre de voix obtenues</th>
        </tr>
        {% for candidat in object_list %}
        <tr>
            <td>{{ candidat.parti }}</td>
            <td>{{ candidat.nb_voix }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

election/templates/election/vote.html
{% extends 'election/base.html' %}

{% block content %}
    <form action="{% url 'election:vote' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Je vote!">
    </form>
{% endblock %}